### ISSUE TITLE
hi andy

### ISSUE THREAD

**Issue by ghost** [andypiper/twauth-web#3]
if you could teach this like i'm 5, it would be invaluable. 
maybe a quick youtube screen recorded walkthrough of how you would run this locally? if you really want to bless us newbies... 
my work is in my repo, if that helps. 

### Expected behavior

i expect it to work as it does on the glitch demo.... 

### Actual behavior

i tried following the read me with heroku locally  — no luck. 
i set callback url in app to "https://gentle-hollows-84884.herokuapp.com.

error: 
Invalid response, status 401, {"errors":[{"code":32,"message":"Could not authenticate you."}]}

**Comment by andypiper** [comment]
Hi there @woodymood - you closed this out (and I'm sorry that I hadn't seen it, I was unavailable for a few days). Did you managed to work out what the issue was? From looking at what you posted, you might have missed `/callback` on the end of the callback URL on the Twitter Developer Dashboard.
